### ISSUE TITLE
Trying to run this snippet but getting block due to credentials issue

### ISSUE THREAD

**Issue by regevguy4** [adamszadkowski/bigquery-emulator-issue#1]
https://github.com/adamszadkowski/bigquery-emulator-issue/blob/91f7a0e475d63c5893cce402250d95d363d8f213/spark-usage/src/test/scala/info/szadkowski/bqissue/spark/BigQueryReadSpec.scala#L57

Hi,
Tried to run locally this code after deployed the BQ-Emulator locally on mty machine. For some reason, the Spark BQ Connector complains about not having credentials (or credentials file) to perform access to the Emulator. Seems like in your case it worked. Maybe you have a clue what am I missing ?

Thanks a lot !

**Comment by adamszadkowski** [comment]
@regevguy4 can you provide instruction how do you run it?

**Comment by regevguy4** [comment]
Sure !
First, I'm running the BQ-Emulator with:

`docker run -it -p 9050:9050  ghcr.io/goccy/bigquery-emulator:latest --project=test`

Its output:

> [bigquery-emulator] REST server listening at 0.0.0.0:9050
> [bigquery-emulator] gRPC server listening at 0.0.0.0:9060


Next, I'm running this Test, which is strongly based on yours:

```
import com.google.cloud.spark.bigquery.repackaged.com.google.cloud.NoCredentials
import com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery._
import org.apache.spark.sql.{DataFrame, SparkSession}
import org.scalatest.FunSuite
import org.scalatest.BeforeAndAfter

import java.util.UUID
import scala.collection.JavaConverters._

class MainTest extends FunSuite with BeforeAndAfter {

  private val projectId = "test"
  private var datasetId: String = _
  private var tableId: String = _

  private lazy val service = BigQueryOptions.newBuilder()
    .setHost("http://localhost:9050")
    .setCredentials(NoCredentials.getInstance())
    .setLocation("EU")
    .setProjectId(projectId)
    .build()
    .getService

  private lazy val sparkSession = SparkSession.builder()
    .master("local")
    .appName("BQ-Emulator-Test")
    .config("bigQueryHttpEndpoint", "http://localhost:9050")
    .config("bigQueryStorageGrpcEndpoint", "localhost:9060")
    .config("readDataFormat", "AVRO")
    .getOrCreate()

  before {
    val random =  UUID.randomUUID().toString.replaceAll("-", "")
    datasetId = s"dataset$random"
    tableId = s"table_a$random"
    service.create(DatasetInfo.newBuilder(projectId, datasetId).setLocation("EU").build())

    val schema = Schema.of(
      Field.of("id", StandardSQLTypeName.STRING),
      Field.of("otherProp", StandardSQLTypeName.STRING)
    )
    service.create(TableInfo.of(TableId.of(projectId, datasetId, tableId), StandardTableDefinition.of(schema)))

    service.insertAll(
      InsertAllRequest.newBuilder(TableId.of(datasetId, tableId))
        .addRow(Map("id" -> "15432", "otherProp" -> "some value here").asJava)
        .build()
    )
  }

  after {
    service.delete(DatasetId.of(projectId, datasetId), BigQuery.DatasetDeleteOption.deleteContents())
  }

  test("loading any data") {
    println(s"$projectId.$datasetId.$tableId")
    val rows = sparkSession
      .read
      .format("bigquery")
      .option("parentProject", projectId)
      .option("projectId", projectId)
      .option("parallelism", 1)
//      .option("credentials", ???)
      .load(s"$projectId.$datasetId.$tableId")
      .collectAsList()
    println(rows)
  }
}
```
And I'm then getting the following Exception:

> 1) Error in custom provider, **java.io.UncheckedIOException: Failed to create default Credentials**
>   at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClientModule.provideBigQueryCredentialsSupplier(BigQueryClientModule.java:46)
>   while locating com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryCredentialsSupplier
>     for the 3rd parameter of com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClientModule.provideBigQueryClient(BigQueryClientModule.java:63)
>   at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClientModule.provideBigQueryClient(BigQueryClientModule.java:63)
>   while locating com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.connector.common.BigQueryClient
>   ...
>   ...
>   ...
>     1 error
> 	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
> 	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097)
> 	at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
> 	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:77)
> 	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:47)
> 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:344)
> 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
> 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:286)
> 	at scala.Option.getOrElse(Option.scala:121)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:232)
> 	at MainTest.$anonfun$new$3(**MainTest.scala:64**)

S.t. MainTest.scala:64 points to - 
>  .load(s"$projectId.$datasetId.$tableId")

I think the _before_ and _after_ blocks working as expected because a _NoCredentials_ object has been provided to the service object, but I'm not sure how to bypass the Credentials issue when trying to read from the BQ-Emulator. What do you think ?

If any more information needed, please let me know.

**Comment by adamszadkowski** [comment]
Examine code in this repo. Especially classes that are hiding original implementation of bigquery library which can be found in here: https://github.com/adamszadkowski/bigquery-emulator-issue/tree/main/spark-usage/src/test/java . Basically bigquery libraries are not "emulator friendly" right now. You can do the same to make it work in your code.

Closing since this issue is not related with this repo.

**Comment by regevguy4** [comment]
You mean you rebuild some of BQ libraries, after adjusting them to work without credentials when working against the BQ-Emulator ?

**Comment by adamszadkowski** [comment]
Rebuild is not exactly the word I would use. I have just copied one of BQ library classes into the project: https://github.com/adamszadkowski/bigquery-emulator-issue/blob/main/spark-usage/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactory.java . I have modified it to fix the issues you are experiencing. Take a look at history of this class and everything should become clear.
